accounts/urls.py
from django.urls import path

from accounts.views import email_capture


app_name = 'accounts'

urlpatterns = [
    path('email-capture/', email_capture, name='email-capture')
]

website/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from views import index


urlpatterns = [
    path('', index, name='index'),
    path('accounts/', include('accounts.urls')),
    path(settings.ADMIN_PATH, admin.site.urls),
]

accounts/models.py
from django.db import models

from website.models import BaseModel


class Signup(BaseModel):
    email = models.EmailField(max_length=200, db_index=True)
    opt_out = models.BooleanField(default=False, db_index=True)

website/models.py
from django.db import models


class BaseModel(models.Model):
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)


    class Meta:
        abstract = True

accounts/views.py
import re

from django.http import JsonResponse

from accounts.models import Signup


def email_capture(request):
    email_address = request.POST.get('email', '')

    # Parse the email string, make sure it's valid
    parsed = email_address.strip().lower()
    if not parsed or not re.match(r'[^@]+@[^@]+\.[^@]+', parsed):
        return JsonResponse({'msg': 'Bad Email'}, status=400)

    # Make sure we don't duplicate emails
    signup, created = Signup.objects.get_or_create(email=parsed)

    if not created:
        return JsonResponse({'msg': 'Already Exists'}, status=400)

    return JsonResponse({'msg': 'Success'})

views.py
from django.shortcuts import render
#use comments always in your code:)

def index(request):
    return render(request, 'index.html', {})

templates/index.html
{% load static %}

<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Electron Network</title>
    <meta name="description" content="Electron Network">
    <meta name="author" content="Electron Network">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'logo.png' %}"/>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-112596720-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];

      function gtag() {
        dataLayer.push(arguments);
      }

      gtag('js', new Date());
      gtag('config', 'UA-112596720-1');
    </script>


    <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->
    <style>
        @font-face {
            font-family: 'Futura';
            src: url('{% static 'fonts/Futura.woff2' %}') format('woff2'),
            url('{% static 'fonts/Futura.woff' %}') format('woff');
        url('{% static 'fonts/Futura.ttf' %}') format('ttf');
            font-weight: normal;
            font-style: normal;
        }

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        html {
            background: #131617;
            color: #95B3B9;
            font-family: 'Lato', sans-serif;
        }

        a {
            text-decoration: none;
        }

        p {
            line-height: 1.618em;
        }

        input {
            border: none;
            background: #011c23;
            color: #E83945;
            padding: 10px;
            border-radius: 5px;
        }

        input:focus {
            outline: none;
        }

        input::placeholder {
            color: #246475;
        }

        button {
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #256375;
            background: none;
            outline: 0;
            color: #FFEDDB;
            cursor: pointer;
            transition: color 250ms ease;
        }

        .cream {
            color: #FFEDDB;
        }

        .rosso {
            color: #E83945;
        }

        .disabled {
            color: #998E84;
        }

        .brand {
            margin: 0 auto;
            max-width: 400px;
            text-align: center;
        }

        section {
            text-align: center;
            width: 100%;
            max-width: 400px;
            padding-bottom: 2rem;
        }

        .brand img {
            max-width: 112px;
        }

        .brand .name {
            font-family: 'Futura', 'sans-serif';;
            font-size: 1.8em;
            text-transform: uppercase;
            padding: 0.5em 0;
        }

        .about {
            padding: 3em 0 1em 0;
        }

        .button {
            padding: 10px;
            margin: 1em;
            border-radius: 5px;
            display: inline-block;
            min-width: 150px;
            border: 1px solid #246475;
        }

        .content {
            min-height: 100vh;
            padding: 2rem 10px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        .contact a {
            margin: 10px 10px;
        }

        .divider-title {
            font-family: 'Futura', 'sans-serif';
            text-transform: uppercase;
            border-bottom: 1px solid #013340;
            width: 100%;
            max-width: 200px;
            margin: 1em;
            padding: 1em;
            text-align: center;
            color: #FFEDDB;
        }

        @media (max-width: 1024px) {
            html {
                font-size: 0.8em;
            }

            .brand img {
                width: 100px;
            }
        }
    </style>
</head>

<body>
<noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KB3Q2BF"
            height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
<div class="content">
    <div class="brand">
        <img src="{% static 'logo.svg' %}" alt="Electron Logo">
        <div class="name rosso">Electron</div>
        <div class="tagline cream">Decentralized Gossip Network made for Humans</div>
    </div>
    <section class="about">
        <p>Electron is a rapid and lightweight P2P library for building decentralized applications</p>
        <a class="button disabled">Whitepaper</a>
    </section>
    <div class="divider-title">Stay Informed</div>
    <section class="contact">
        <form method="post" id="email-capture">
            {% csrf_token %}
            <input type="email" name="email" required title="email" placeholder="Enter your Email">
            <button type="submit">Submit</button>
        </form>
    </section>
    <div class="divider-title">Get Involved</div>
    <section class="contact">
        <a href="https://t.me/electronnetwork" target="_blank" class="button cream">Telegram</a>
        <a href="https://github.com/electron-network" target="_blank" class="button cream">GitHub</a>
    </section>
</div>
<script type="text/javascript">
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = cookies[i].trim();

        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }

  window.addEventListener("load", function () {
    function changeForm(payload) {
      submitButton.innerText = payload.msg;
      submitButton.classList.toggle('rosso');
      setTimeout(function () {
        form.reset();
        submitButton.innerText = "Submit";
        submitButton.classList.toggle('rosso');
      }, 3000);
    }

    function sendData() {
      var XHR = new XMLHttpRequest();
      var FD = new FormData(form);

      XHR.addEventListener("load", function (event) {
        changeForm(JSON.parse(event.target.responseText))
      });

      XHR.addEventListener("error", function (event) {
        changeForm(JSON.parse(event.target.responseText))
      });

      XHR.open("POST", "{% url 'accounts:email-capture' %}");
      XHR.setRequestHeader('X-CSRF-Token', getCookie('csrftoken'));
      XHR.send(FD);
    }

    var form = document.getElementById("email-capture");
    var submitButton = form.querySelector("button");

    form.addEventListener("submit", function (event) {
      event.preventDefault();
      sendData();
    });
  });

</script>
</body>
</html>